# Generated by Django 5.2 on 2025-06-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Designation', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='record')),
                ('Department_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
