# Generated by Django 5.2 on 2025-05-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Language', models.CharField(max_length=200)),
                ('Pages', models.IntegerField()),
                ('Image', models.ImageField(upload_to='books')),
            ],
        ),
    ]
